# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
- repo: self
  clean: true

trigger:
- release/*
- feature/*
- fix/*
- master

variables:
  service: "app0"
  layer: "frontend"
  build: $(Build.BuildId)
  env: "BUILD"
  GENERATE_SOURCEMAP: false
  ENVIRONMENT: "PROD"

jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: divoianhacr.azurecr.io
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: divoianhacr.azurecr.io/$(service)
        tags: |
          $(Build.BuildId)
          latest