apiVersion: v1
kind: Service
metadata:
  name: app-0-lb
  namespace: development
spec:
  type: LoadBalancer
  ports:
  - protocol: 
    port: 80
    targetPort: 3000
  selector:
    app: app-0
    tier: frontend